# Generated by Django 4.1.1 on 2022-09-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
